weighted = ("Overhead Presses",
            "Plank Walkouts",
            "Dumbbell Presses",
            "Bicep Curls",
            "Palms-up wrist curl",
            "Palms-down Wrist Curls",
            "Concentration curls",
            "Triceps Kickback",
            "Triceps Dip",
            "Overhead Triceps Extension",
            "Dumbbell Floor Press",
            "Plank with Biceps Curl",
            "Lying Overhead Triceps Extension")

not_weighted = ( "Push-Ups",
                 "Pull-Ups",
                 "Bear Crawl",
                 "Plank taps",
                 "Side Planks",
                 "Forearm Plank Reach Out",
                 "Plank up-down",
                 "Lateral Plank Walk",
                 "Body Saw",
                 "Bodywieght Tricep dips",
                 "Inchworm",
                 "Porearm Plank to Dolpin",
                 "Plank Jack",
                 "Burpee with Push-ups"
                 )