not_weighted = ( "Forearm Plank",
                 "Bird Dog Crunch",
                 "Bear Crawl",
                 "Plank taps",
                 "Side Planks",
                 "Forearm Plank Reach Out",
                 "Plank up-down",
                 "Lateral Plank Walk",
                 "Body Saw",
                 "Bodywieght Tricep dips",
                 "Inchworm",
                 "Porearm Plank to Dolpin",
                 "Plank Jack",
                 "Plank Hop",
                 "Leg Lift",
                 "Down Dog Abs",
                 "Dead Bug",
                 "Core Roll Up",
                 "Bicycle Crunch",
                 "Crab Toe Touch",
                 "Mountain Climber",
                 "Rainbow Plank",
                 "Single-Leg Jackknife",
                 "Jackknife",
                 "Forearm Side Plank Hip Dip",
                 "Forearm Side Plank With Twist",
                 "Scissor Switch",
                 "Warrior Balance",
                 "Russian Twist",
                 "Boat Pose",
                 "Pilates 100"
                 )